version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - F:\Workspace\WordPress\nginx:/etc/nginx/conf.d
      - F:\Workspace\WordPress\logs/nginx:/var/log/nginx
      - F:\Workspace\WordPress\wordpress:/var/www/html
      - F:\Workspace\WordPress\certs:/etc/letsencrypt
      - F:\Workspace\WordPress\certs-data:/data/letsencrypt
    links:
      - wordpress
    restart: always

  mysql:
    image: mariadb
    container_name: mysql
    volumes:
      - F:\Workspace\WordPress\config:/etc/mysql/conf.d
      - F:\Workspace\WordPress\mysql:/var/lib/mysql

    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: always

  wordpress:
    image: wordpress:php7.2-fpm
    container_name: wordpress
    volumes:
      - F:\Workspace\WordPress\wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_PASSWORD=password
    links:
      - mysql
    restart: always
